### ISSUE TITLE
problem with storage mongodb

### ISSUE THREAD

**Issue by mattsjakobsson** [CanonicalLtd/candid#110]
Hi

We have problems when using storage mongodb as backing storage.

output from mongodb
2018-11-26T11:42:44.673+0100 [initandlisten] connection accepted from 127.0.0.1:58906 #1 (1 connection now open)
2018-11-26T11:42:44.680+0100 [conn1] allocating new ns file /var/lib/mongodb/candid.ns, filling with zeroes...
2018-11-26T11:42:44.860+0100 [FileAllocator] allocating new datafile /var/lib/mongodb/candid.0, filling with zeroes...
2018-11-26T11:42:44.877+0100 [FileAllocator] done allocating datafile /var/lib/mongodb/candid.0, size: 64MB,  took 0.015 secs
2018-11-26T11:42:44.877+0100 [conn1] build index on: candid.identities properties: { v: 1, key: { _id: 1 }, name: "_id_", ns: "candid.identities" }
2018-11-26T11:42:44.877+0100 [conn1]     added index to empty collection
2018-11-26T11:42:44.878+0100 [conn1] build index on: candid.identities properties: { v: 1, unique: true, key: { username: 1 }, name: "username_1", ns: "candid.identities" }
2018-11-26T11:42:44.878+0100 [conn1]     added index to empty collection
2018-11-26T11:42:44.878+0100 [conn1] command candid.$cmd command: createIndexes { createIndexes: "identities", indexes: [ { name: "username_1", ns: "candid.identities", key: { username: 1 }, unique: true } ] } keyUpdates:0 numYields:0 locks(micros) W:93 r:9 w:197755 reslen:113 197ms
2018-11-26T11:42:44.878+0100 [conn1] build index on: candid.identities properties: { v: 1, unique: true, key: { providerid: 1 }, name: "providerid_1", ns: "candid.identities" }
2018-11-26T11:42:44.879+0100 [conn1]     added index to empty collection
2018-11-26T11:42:44.893+0100 [conn1] build index on: candid.meeting properties: { v: 1, key: { _id: 1 }, name: "_id_", ns: "candid.meeting" }
2018-11-26T11:42:44.893+0100 [conn1]     added index to empty collection
2018-11-26T11:42:44.894+0100 [conn1] build index on: candid.meeting properties: { v: 1, key: { addr: 1, created: 1 }, name: "addr_1_created_1", ns: "candid.meeting" }
2018-11-26T11:42:44.894+0100 [conn1]     added index to empty collection
2018-11-26T11:42:44.894+0100 [conn1] build index on: candid.meeting properties: { v: 1, key: { created: 1 }, name: "created_1", ns: "candid.meeting" }
2018-11-26T11:42:44.894+0100 [conn1]     added index to empty collection
2018-11-26T11:42:44.895+0100 [conn1] build index on: candid.macaroons properties: { v: 1, key: { _id: 1 }, name: "_id_", ns: "candid.macaroons" }
2018-11-26T11:42:44.895+0100 [conn1]     added index to empty collection
2018-11-26T11:42:44.895+0100 [conn1] build index on: candid.macaroons properties: { v: 1, key: { created: -1 }, name: "created_-1", ns: "candid.macaroons" }
2018-11-26T11:42:44.896+0100 [conn1]     added index to empty collection
2018-11-26T11:42:44.896+0100 [conn1] build index on: candid.macaroons properties: { v: 1, key: { expires: 1 }, name: "expires_1", ns: "candid.macaroons", expireAfterSeconds: 1 }
2018-11-26T11:42:44.896+0100 [conn1]     added index to empty collection
2018-11-26T11:42:44.897+0100 [conn1] build index on: candid.acls properties: { v: 1, key: { _id: 1 }, name: "_id_", ns: "candid.acls" }
2018-11-26T11:42:44.897+0100 [conn1]     added index to empty collection
2018-11-26T11:42:44.897+0100 [conn1] build index on: candid.acls properties: { v: 1, key: { expire: 1 }, name: "expire_1", ns: "candid.acls", expireAfterSeconds: 1 }
2018-11-26T11:42:44.897+0100 [conn1]     added index to empty collection
2018-11-26T11:42:44.898+0100 [conn1] end connection 127.0.0.1:58906 (0 connections now open)
2018-11-26T11:42:45.209+0100 [initandlisten] connection accepted from 127.0.0.1:58908 #2 (1 connection now open)
2018-11-26T11:42:45.212+0100 [conn2] end connection 127.0.0.1:58908 (0 connections now open)
2018-11-26T11:42:45.472+0100 [initandlisten] connection accepted from 127.0.0.1:58910 #3 (1 connection now open)
2018-11-26T11:42:45.475+0100 [conn3] end connection 127.0.0.1:58910 (0 connections now open)
2018-11-26T11:42:45.723+0100 [initandlisten] connection accepted from 127.0.0.1:58912 #4 (1 connection now open)
2018-11-26T11:42:45.727+0100 [conn4] end connection 127.0.0.1:58912 (0 connections now open)
2018-11-26T11:42:45.956+0100 [initandlisten] connection accepted from 127.0.0.1:58914 #5 (1 connection now open)
2018-11-26T11:42:45.960+0100 [conn5] end connection 127.0.0.1:58914 (0 connections now open)
2018-11-26T11:43:01.650+0100 [clientcursormon] mem (MB) res:44 virt:541
2018-11-26T11:43:01.650+0100 [clientcursormon]  mapped (incl journal view):320
2018-11-26T11:43:01.650+0100 [clientcursormon]  connections:0
2018-11-26T11:48:01.666+0100 [clientcursormon] mem (MB) res:45 virt:541
2018-11-26T11:48:01.666+0100 [clientcursormon]  mapped (incl journal view):320
2018-11-26T11:48:01.666+0100 [clientcursormon]  connections:0

Output from candid in syslog
Nov 26 11:48:48 causal-quagga systemd[1]: Started Service for snap application candid.candidsrv.
Nov 26 11:48:48 causal-quagga candid.candidsrv[13439]: 2018-11-26 10:48:48 INFO candid.store.mgostore config.go:42 connecting to mongo
Nov 26 11:48:48 causal-quagga candid.candidsrv[13439]: 2018-11-26 10:48:48 INFO candidsrv main.go:104 setting up the identity server
Nov 26 11:48:48 causal-quagga candid.candidsrv[13439]: panic: Session already closed
Nov 26 11:48:48 causal-quagga candid.candidsrv[13439]: goroutine 1 [running]:
Nov 26 11:48:48 causal-quagga candid.candidsrv[13439]: gopkg.in/mgo%2ev2.(*Session).cluster(...)
Nov 26 11:48:48 causal-quagga candid.candidsrv[13439]: #011/root/go/pkg/mod/gopkg.in/mgo.v2@v2.0.0-20180705113604-9856a29383ce/session.go:1624
Nov 26 11:48:48 causal-quagga candid.candidsrv[13439]: gopkg.in/mgo%2ev2.copySession(0xc0002384e0, 0x1, 0xc00033d160)
Nov 26 11:48:48 causal-quagga candid.candidsrv[13439]: #011/root/go/pkg/mod/gopkg.in/mgo.v2@v2.0.0-20180705113604-9856a29383ce/session.go:540 +0x391
Nov 26 11:48:48 causal-quagga candid.candidsrv[13439]: gopkg.in/mgo%2ev2.(*Session).Copy(0xc0002384e0, 0xaf7200)
Nov 26 11:48:48 causal-quagga candid.candidsrv[13439]: #011/root/go/pkg/mod/gopkg.in/mgo.v2@v2.0.0-20180705113604-9856a29383ce/session.go:1590 +0x40
Nov 26 11:48:48 causal-quagga candid.candidsrv[13439]: github.com/juju/simplekv/mgosimplekv.(*kvStore).session(0xc00000e0b0, 0xc9ba00, 0xc0000240b8, 0x0)
Nov 26 11:48:48 causal-quagga candid.candidsrv[13439]: #011/root/go/pkg/mod/github.com/juju/simplekv@v0.0.0-20180621131638-ff82918775e5/mgosimplekv/kv.go:59 +0x99
Nov 26 11:48:48 causal-quagga candid.candidsrv[13439]: github.com/juju/simplekv/mgosimplekv.(*kvStore).c(0xc00000e0b0, 0xc9ba00, 0xc0000240b8, 0xc00033cf88)
Nov 26 11:48:48 causal-quagga candid.candidsrv[13439]: #011/root/go/pkg/mod/github.com/juju/simplekv@v0.0.0-20180621131638-ff82918775e5/mgosimplekv/kv.go:66 +0x4b
Nov 26 11:48:48 causal-quagga candid.candidsrv[13439]: github.com/juju/simplekv/mgosimplekv.(*kvStore).Update(0xc00000e0b0, 0xc9ba00, 0xc0000240b8, 0xbc7fe2, 0x5, 0x0, 0x0, 0x0, 0xc00034f0e0, 0x0, ...)
Nov 26 11:48:48 causal-quagga candid.candidsrv[13439]: #011/root/go/pkg/mod/github.com/juju/simplekv@v0.0.0-20180621131638-ff82918775e5/mgosimplekv/kv.go:116 +0x68
Nov 26 11:48:48 causal-quagga candid.candidsrv[13439]: github.com/juju/aclstore/v2.(*kvStore).CreateACL(0xc000075a40, 0xc9ba00, 0xc0000240b8, 0xbc7fe2, 0x5, 0xc000075d20, 0x1, 0x1, 0xabdd00, 0x1)
Nov 26 11:48:48 causal-quagga candid.candidsrv[13439]: #011/root/go/pkg/mod/github.com/juju/aclstore/v2@v2.0.0-alpha2/store.go:74 +0xe5
Nov 26 11:48:48 causal-quagga candid.candidsrv[13439]: github.com/juju/aclstore/v2.NewManager(0xc9ba00, 0xc0000240b8, 0xc9c780, 0xc000075a40, 0xc000075d20, 0x1, 0x1, 0x0, 0x0, 0x0)
Nov 26 11:48:48 causal-quagga candid.candidsrv[13439]: #011/root/go/pkg/mod/github.com/juju/aclstore/v2@v2.0.0-alpha2/manager.go:80 +0x88
Nov 26 11:48:48 causal-quagga candid.candidsrv[13439]: github.com/CanonicalLtd/candid/internal/identity.New(0xc9c6c0, 0xc00000e0c8, 0xc935a0, 0xc00000e0c0, 0xc968e0, 0xc00000dc80, 0xc9c680, 0xc00000e0b8, 0x0, 0x0, ...)
Nov 26 11:48:48 causal-quagga candid.candidsrv[13439]: #011/build/candid/parts/candid/build/internal/identity/server.go:72 +0x34a
Nov 26 11:48:48 causal-quagga candid.candidsrv[13439]: github.com/CanonicalLtd/candid.NewServer(0xc9c6c0, 0xc00000e0c8, 0xc935a0, 0xc00000e0c0, 0xc968e0, 0xc00000dc80, 0xc9c680, 0xc00000e0b8, 0x0, 0x0, ...)
Nov 26 11:48:48 causal-quagga candid.candidsrv[13439]: #011/build/candid/parts/candid/build/server.go:136 +0x2c3
Nov 26 11:48:48 causal-quagga candid.candidsrv[13439]: main.serveIdentity(0xc0002a40f0, 0xc9c6c0, 0xc00000e0c8, 0xc935a0, 0xc00000e0c0, 0xc968e0, 0xc00000dc80, 0xc9c680, 0xc00000e0b8, 0x0, ...)
Nov 26 11:48:48 causal-quagga candid.candidsrv[13439]: #011/build/candid/parts/candid/build/cmd/candidsrv/main.go:129 +0x426
Nov 26 11:48:48 causal-quagga candid.candidsrv[13439]: main.serve(0xc0002a40f0, 0x0, 0x0)
Nov 26 11:48:48 causal-quagga candid.candidsrv[13439]: #011/build/candid/parts/candid/build/cmd/candidsrv/main.go:93 +0x337
Nov 26 11:48:48 causal-quagga candid.candidsrv[13439]: main.main()
Nov 26 11:48:48 causal-quagga candid.candidsrv[13439]: #011/build/candid/parts/candid/build/cmd/candidsrv/main.go:61 +0x1cd
Nov 26 11:48:48 causal-quagga systemd[1]: snap.candid.candidsrv.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Nov 26 11:48:48 causal-quagga systemd[1]: snap.candid.candidsrv.service: Unit entered failed state.

Somehow it seems like 
The session is closed before copied somwhere.

/M

**Comment by mhilton** [comment]
This is now fixed

**Comment by mattsjakobsson** [comment]
works great, thank you very much
